#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp"
env_files = [".devcontainer/.env"]

[build]
pre_cmd = [
  "npm run build:css",
  "npm run build:js",
  "go run github.com/a-h/templ/cmd/templ@latest generate -path web",
]
cmd = 'go build -ldflags="-s -w -X github.com/joshuar/go-hass-agent/config.AppVersion=$(git describe --tags --always --long --dirty)" -o ./tmp/go-hass-agent .'
args_bin = [
  "--profile='heapprofile=tmp/heap.prof;cpuprofile=tmp/cpu.prof;webui=true'",
  "run",
]
entrypoint = ["tmp/go-hass-agent"]
bin = "tmp/go-hass-agent"
cdelay = 1000
exclude_dir = [
  "bin",
  "dist",
  "node_modules",
  "web/content",
  "tmp",
  "tests",
  "vendor",
  "_archive",
  "schema",
]
exclude_regex = ["_test\\.go", "_templ\\.go"]
exclude_unchanged = false
follow_symlink = false
include_ext = ["go", "templ", "html", "json", "js", "ts", "css", "scss"]
kill_delay = 500
log = "deployments/build-errors-air.log"
poll = false
poll_interval = 500
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[log]
main_only = false
time = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
